services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'admin123'
      MYSQL_DATABASE: 'flask-crud'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '123'
    ports:
      - "3307:3306"
    expose:
      - "3306"
    volumes:
      - /Users/lzabreu/DEV/IGNITE/python/modulo_4/mysql:/var/lib/mysql
